apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cluster-config
  namespace: kafka

data:
  CLUSTER_ID: hljM2T6EQdSKyVaXRttpCg
  CONTROLLER_REPLICAS: "{{ .Values.controllerReplicas }}"
  BROKER_REPLICAS: "{{ .Values.brokerReplicas }}"

  broker.properties: |
    process.roles=broker
    controller.listener.names=CONTROLLER
    listener.security.protocol.map: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data
  controller.properties: |
    process.roles=controller
    controller.listener.names=CONTROLLER
    listeners=CONTROLLER://:9091
    log.dirs=/var/lib/kafka/data