apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default "kafka-service-account" }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}