apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.microservice.name }}-http-route
spec:
  parentRefs:
  - name: gateway
    namespace: {{ .Values.gateway_service.namespace }}
  hostnames: {{ .Values.httprouts.hostnames }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.httprouts.path | default "/{{ .Values.microservice.name}}" }}
    backendRefs:
    - name: {{ .Values.microservice.name }}-service
      port: {{ .Values.service.port }}







# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: http
#   namespace: default
# spec:
#   parentRefs:
#   - name: gateway
#     namespace: istio-ingress
#   hostnames: ["httpbin.example.com"]
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /get
#     backendRefs:
#     - name: httpbin
#       port: 8000