apiVersion: v1
entries:
  kafka-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-17T09:46:20.8755533+05:30"
    description: A Helm chart for Kubernetes
    digest: b7d1a9154eb7f5cfc901fac1a3fc353671411c4edac466f82b12f1bf2177f220
    name: kafka-helm-chart
    type: application
    urls:
    - kafka-helm-chart-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-17T09:46:20.8697362+05:30"
