apiVersion: v1
entries:
  certified_gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-09-18T19:35:29.2695848+05:30"
    description: A Helm chart for Kubernetes
    digest: 7a616644d690deb3d2539eb6f80b114f8640167ca3989b39ff1e699f8d0a257c
    name: certified_gateway
    type: application
    urls:
    - certified_gateway-0.1.0.tgz
    version: 0.1.0
  hrms-microservices:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-09-18T19:35:29.2961349+05:30"
    description: A Helm chart for Microservices in hrms
    digest: da8121f9f4d76f98fe9c5a2628cf80b1bb01db8e32a86ab5f01439830680c80a
    name: hrms-microservices
    type: application
    urls:
    - hrms-microservices-0.1.0.tgz
    version: 0.1.0
  kafka-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-09-18T19:35:29.3109811+05:30"
    description: A Helm chart for Kubernetes
    digest: b7d1a9154eb7f5cfc901fac1a3fc353671411c4edac466f82b12f1bf2177f220
    name: kafka-helm-chart
    type: application
    urls:
    - kafka-helm-chart-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-09-18T19:35:29.3120865+05:30"
    description: A Helm chart for Kubernetes
    digest: a53e9b4ebe6591561a8423cd325b3707d457e9dbf503d1c1cff73176ddc1f534
    name: redis
    type: application
    urls:
    - redis-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-18T19:35:29.2386436+05:30"
